generate_monthly_ntd_report:
	uv run python download_monthly_ntd.py
	uv run python prep_monthly_ntd.py
	uv run python publish_monthly_ntd.py

generate_annual_ntd_report:
	uv run python download_annual_ntd.py
	uv run python prep_annual_ntd.py
	uv run python publish_annual_ntd.py
